name: Update Growth Notebook
on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    
    - name: install dependencies
      run: |
        pip install matplotlib pandas seaborn papermill ipykernel jupyter
        python3 -m ipykernel install --user --name python3
        sudo chmod -R 777 .
        cd _notebooks
        papermill covid19_growth.ipynb covid19_growth.ipynb

    - name: update notebook
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add _notebooks/covid19_growth.ipynb
        git add images/diagram.png
        git commit -m'update covid19_growth.ipynb'
        git push
